import = [
    # "~/.config/alacritty/themes/themes/alabaster_dark.toml"
    # "~/.config/alacritty/themes/themes/tomorrow_night_bright.toml"
    "~/.config/alacritty/themes/themes/monokai_charcoal.toml",
]

[env]
TERM = "xterm-256color"
